name: Build - Meson
on: 
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "./github/**"
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    - uses: actions/upload-artifact@v2
      with:
        name: peregrine-build
        path: ./builddir/peregrine.elf
        retention-days: 1
        if-no-files-found: error
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Meson
      run: sudo apt-get update && sudo apt-get install python3 python3-pip python3-setuptools nodejs python3-wheel ninja-build && pip3 install meson
    - name: Meson
      run: meson builddir
    - name: Ninja
      run: cd builddir && ninja
    
run-tests:
    needs: build
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install build-essential
        run: sudo apt-get install build-essential
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifact Compiled peregrine
        uses: actions/download-artifact@v2
        with:
          name: peregrine-bin
          path: ./builddir/
      - name: Run tests
        run: | 
          cd builddir
          ls
          pwd
          sudo chmod 777 ./peregrine.elf
          sudo bash ./run_tests_ci.sh
          ./peregrine.elf -dev_debug && /peregrine.elf compile ../can_comp.pe -o output && /peregrine.elf compile ../can_comp.js.pe -o output.js
          ./output && node ./output.js
          echo TEST DONE