# Action to build Peregrine and run the tests. Original Version by CLientCrash 7 - Okt - 2021
name: Build Peregrine with Vlang
on: [push,pull_request]
jobs:
  build-peregrine:
    name: Build Peregrine
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: latest
      id: v
    - name: Build Peregrine
      run: |
        v ./Peregrine/peregrine.v -o peregrine -path='builtin/'
        ls
    - uses: actions/upload-artifact@v2
      with:
        name: peregrine-bin
        path: peregrine
  run-tests:
    needs: build-peregrine
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Download Artifact Compiled peregrine
        uses: actions/download-artifact@v2
        with:
          name: peregrine-bin
          path: ./Peregrine/
      - name: Run tests
        run: | 
          sudo apt-get install build-essential
          cd Peregrine
          sudo chmod +x peregrine
          sudo python test_runner.py
          echo TEST DONE