name: Build Peregrine with Vlang
on: [push,pull_request]
jobs:
  build-peregrine:
    name: Build Peregrine
    runs-on: ubuntu-latest
    needs: build-v
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: latest
      id: v
    - name: Build Peregrine
      run: |
        ls
        sudo su
        chmod 777 ./v
        v ./Peregrine/peregrine.v -o peregrine -path='builtin/'