name: Build - Meson
on: 
  pull_request:
    branches:
      - "main"
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Meson
      run: sudo apt-get update && sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build && pip3 install meson
    - name: Meson
      run: meson builddir
    - name: Ninja
      run: cd builddir && ninja
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: builddir/peregrine.elf
        retention-days: 1
  jscompile:
    name: JS Compile Test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: build
        path: pelf
    - run: cd ./pelf
    - run: ls
    - run: ./peregrine.elf -dev_debug && ./peregrine.elf compile ../can_comp.pe -o output && ./peregrine.elf compile ../can_comp.js.pe -o output.js
    - run: ./output && node ./output.js
